apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
  namespace: kafka
  labels:
    app: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      nodeSelector:
        agentpool: kafkapool
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka:7.8.0
        ports:
        - containerPort: 9092
        - containerPort: 9094
        - containerPort: 9999
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka1:9092,EXTERNAL://134.33.24.51:30502
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_LISTENERS
          value: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LOG4J_LOGGERS
          value: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_JMX_PORT
          value: "9999"
        - name: KAFKA_JMX_HOSTNAME
          value: localhost
        - name: KAFKA_AUTHORIZER_CLASS_NAME
          value: kafka.security.authorizer.AclAuthorizer
        - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
          value: "true"
