apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb-server
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb-server
  template:
    metadata:
      labels:
        app: ksqldb-server
    spec:
      containers:
      - name: ksqldb-server
        image: confluentinc/cp-ksqldb-server:7.8.0
        ports:
        - containerPort: 8088
        env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: "PLAINTEXT://kafka1:9092"
        - name: KSQL_LISTENERS
          value: "http://0.0.0.0:8088/"
        - name: KSQL_KSQL_SERVICE_ID
          value: "ksqldb-server_"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /info
            port: 8088
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /info
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: ksqldb-state
          mountPath: /ksqldb/state
      volumes:
      - name: ksqldb-state
        emptyDir: {} # For ephemeral state; use PVC for persistence
      nodeSelector:
        agentpool: kafkapool
